version: "3.8"

services:
  backend:
    image: arisdev2k2/backend-easydine:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_LIFE=${ACCESS_TOKEN_LIFE}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_LIFE=${REFRESH_TOKEN_LIFE}
      - REFRESH_TOKEN_SIZE=${REFRESH_TOKEN_SIZE}
      - END_TIME_OFFSET_MINUTES=${END_TIME_OFFSET_MINUTES}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - FE_URL=${FE_URL}
      - VT_ENV=${VT_ENV}
    networks:
      - mongo_app-network

networks:
  mongo_app-network:
    external: true
