version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - mongo_app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aris
      - MONGO_INITDB_ROOT_PASSWORD=thang.vv215643
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_app-network

volumes:
  mongo_data:

networks:
  mongo_app-network:
    external: true