version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - mongo_app-network

networks:
  mongo_app-network:
    external: true