name: Deploy be-EasyDine to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/aris/be-EasyDine
            git pull origin main
            npm install
            if pm2 list | grep -q "be-EasyDine"; then
              pm2 restart be-EasyDine
            else
              pm2 start npm --name "be-EasyDine" -- run start --prefix /home/aris/be-EasyDine
            fi
            pm2 save

      - name: Check Server Health
        run: |
          sleep 10
          curl -f https://vuvanthang.website || exit 1