name: Deploy be-EasyDine Backend to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: arisdev2k2/backend-easydine:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        env:
          PORT: ${{ secrets.PORT }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          ACCESS_TOKEN_LIFE: ${{ secrets.ACCESS_TOKEN_LIFE }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          REFRESH_TOKEN_LIFE: ${{ secrets.REFRESH_TOKEN_LIFE }}
          REFRESH_TOKEN_SIZE: ${{ secrets.REFRESH_TOKEN_SIZE }}
          END_TIME_OFFSET_MINUTES: ${{ secrets.END_TIME_OFFSET_MINUTES }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          VT_ENV: ${{ secrets.VT_ENV }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: PORT,MONGO_URI,ACCESS_TOKEN_SECRET,ACCESS_TOKEN_LIFE,REFRESH_TOKEN_SECRET,REFRESH_TOKEN_LIFE,REFRESH_TOKEN_SIZE,END_TIME_OFFSET_MINUTES,EMAIL_USER,EMAIL_PASS,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,GOOGLE_CALLBACK_URL,SESSION_SECRET,VT_ENV,FRONTEND_URL
          script: |
            # Update code from repository
            cd ~/backend-easydine
            git pull origin main

            # Create network if not exists
            if ! docker network ls | grep -q mongo_app-network; then
              docker network create mongo_app-network
            fi

            # Pull latest image
            docker pull arisdev2k2/backend-easydine:latest
            docker-compose down

            # Run docker-compose with all environment variables
            PORT="${PORT}" \
            MONGO_URI="${MONGO_URI}" \
            ACCESS_TOKEN_SECRET="${ACCESS_TOKEN_SECRET}" \
            ACCESS_TOKEN_LIFE="${ACCESS_TOKEN_LIFE}" \
            REFRESH_TOKEN_SECRET="${REFRESH_TOKEN_SECRET}" \
            REFRESH_TOKEN_LIFE="${REFRESH_TOKEN_LIFE}" \
            REFRESH_TOKEN_SIZE="${REFRESH_TOKEN_SIZE}" \
            END_TIME_OFFSET_MINUTES="${END_TIME_OFFSET_MINUTES}" \
            EMAIL_USER="${EMAIL_USER}" \
            EMAIL_PASS="${EMAIL_PASS}" \
            GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID}" \
            GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET}" \
            GOOGLE_CALLBACK_URL="${GOOGLE_CALLBACK_URL}" \
            SESSION_SECRET="${SESSION_SECRET}" \
            VT_ENV="${VT_ENV}" \
            FRONTEND_URL="${FRONTEND_URL}" \
            docker-compose up -d

            # Clean up old images
            docker image prune -f
