name: Deploy be-EasyDine Backend to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Đảm bảo Docker và Docker Compose được cài đặt
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ${{ secrets.SERVER_USER }}
            fi
            if ! command -v docker-compose &> /dev/null; then
              sudo apt install -y docker-compose
            fi

            # Tạo thư mục secrets
            mkdir -p /home/aris/backend-easydine/secrets

            # Tạo các file secrets (tên in hoa)
            echo "${{ secrets.MONGO_URI }}" > /home/aris/backend-easydine/secrets/MONGO_URI
            echo "${{ secrets.ACCESS_TOKEN_SECRET }}" > /home/aris/backend-easydine/secrets/ACCESS_TOKEN_SECRET
            echo "${{ secrets.ACCESS_TOKEN_LIFE }}" > /home/aris/backend-easydine/secrets/ACCESS_TOKEN_LIFE
            echo "${{ secrets.REFRESH_TOKEN_SECRET }}" > /home/aris/backend-easydine/secrets/REFRESH_TOKEN_SECRET
            echo "${{ secrets.REFRESH_TOKEN_LIFE }}" > /home/aris/backend-easydine/secrets/REFRESH_TOKEN_LIFE
            echo "${{ secrets.REFRESH_TOKEN_SIZE }}" > /home/aris/backend-easydine/secrets/REFRESH_TOKEN_SIZE
            echo "${{ secrets.END_TIME_OFFSET_MINUTES }}" > /home/aris/backend-easydine/secrets/END_TIME_OFFSET_MINUTES
            echo "${{ secrets.EMAIL_USER }}" > /home/aris/backend-easydine/secrets/EMAIL_USER
            echo "${{ secrets.EMAIL_PASS }}" > /home/aris/backend-easydine/secrets/EMAIL_PASS

            # Thiết lập quyền cho các file secrets
            chmod 600 /home/aris/backend-easydine/secrets/*

            # Triển khai backend
            cd /home/aris/backend-easydine
            git pull origin main
            docker-compose down
            docker-compose up -d --build

      - name: Check Server Health
        run: |
          sleep 10
          curl -f https://vuvanthang.website || exit 1