name: Deploy be-EasyDine Backend to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Đảm bảo Docker và Docker Compose được cài đặt
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ${{ secrets.SERVER_USER }}
            fi
            if ! command -v docker-compose &> /dev/null; then
              sudo apt install -y docker-compose
            fi

            # Load image node:18 nếu cần
            if ! docker image inspect node:18 >/dev/null 2>&1; then
              if [ -f /home/aris/node18.tar ]; then
                docker load -i /home/aris/node18.tar
              else
                echo "Image node:18 and backup tar file not found. Please provide the image."
                exit 1
              fi
            fi

            # Triển khai backend
            cd /home/aris/backend-easydine
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            # Dọn dẹp image không dùng
            docker image prune -f

      - name: Check Server Health
        run: |
          sleep 30
          curl -f https://vuvanthang.website || exit 1